
max:
	g++ max.cpp -o ./main
	./main 

test:
	g++ testnutil.cpp ../nutils.cpp -o ./test 
	./test

max3:
	g++ max3.cpp ../nutils.cpp -o ./max3
	./max3

clean:
	rm -f ./main
	rm -f ./max3

cleant:
	rm -f ./test
